module.exports.config = {
  name: "Bot",
  version: "5.0.0",
  hasPermssion: 0,
  credits: "ZAKHMI SAYAR",
  description: "200 Text + 193 Emoji All Reply",
  commandCategory: "Noprefix",
  usages: "noprefix",
  cooldowns: 2,
};

module.exports.handleEvent = async function({ api, event }) {
  const { threadID, messageID } = event;
  if (!event.body) return;
  const body = event.body.toLowerCase().trim();
  const raw = event.body.trim();

  const tl = [
    "TUM MERE BOSS ZAKHMI SAYAR KI GF BAN JAO LDKI🙈",
    "Bot nah bol oye, Janu bol mujhy 🥺",
    "Haweli pe mil zara bataunga 😂",
    "Shakal se masoom lagte ho 😂",
    "Kash tum single hote to maza hi kuch aur tha 😂",
    "Ab yaad ayi meri? Pehle to babu shona me busy the 😾",
    "Roti banana ke liye aate me paani daalte hain 😂",
    "Aise na dekho pyaar ho jayega 😂",
    "Teri pic dekhne se pehle shukar hai mai andha hu 😂",
    "Haste raho, hasne se bill nahi aata 😂",
    "Mujhse shadi karlo, daily chocolate dunga 🍫",
    "Ajao pizza khilau apko 🍕",
    "Duniya me sab khatam ho sakta, logo ki bakwas nahi 😂",
    "Everything is temporary, but katna is permanent 😂",
    "Ameer larki set karke sab ka udhar wapis karunga 😔",
    "Lagta hai career bhi Titanic ki tarah doob gaya 💔",
    "Itna single hu khwab me bhi ladki han kare to ankh khul jati 🙂",
    "Move on karle bhai kab tak uski profile dekhega",
    "Bot jaan hai sabki 🌸",
    "Ib ajao chup chup ke baatein karte hain 🙈",
    "Tumhare bina group suna suna lagta hai janu 😜",
    "Mehfil me chaar chaand laga diye tumne aake 🌙",
    "Dil garden garden ho gaya tumhe dekh ke 🌸",
    "Aaj toh bada handsome lag raha hai tu 😎",
    "Chai pani puch lo, itna kanjoos mat bano ☕",
    "Tumhari yaad me raat bhar so nahi paya 😴",
    "Haye tumhari ye ada, maar hi dalegi ek din 😍",
    "Group ka star hai tu 🌟",
    "Itna cute DP kisne lagane bola tha 😍",
    "Tumhari smile pe duniya qurban 🥰",
    "Dekh ke dil khush ho gaya ❤️",
    "Aaj toh party banti hai 🎉",
    "Haye garmi, tum itne hot kyun ho 🔥",
    "Bas karo, itna mat hasao pet dukh raha hai 🤣",
    "Tumhari baaton me jadoo hai ✨",
    "Tum toh meri jaan ho yaar 😘",
    "Yaar tum kitne cute ho 🥺",
    "Tum toh dil jeet lete ho har baar ❤️",
    "Tum toh chand ka tukda ho 🌙",
    "Oye janeman, kya haal hai? 😜",
    "Aaj toh tum aag laga rahe ho 🔥",
    "Tumhari smile killer hai 😍",
    "Dil me bas tum hi tum ho 💚",
    "Tum toh dil ka sukoon ho 🥰",
    "Oye paglu, kya kar raha hai? 😂",
    "Tum toh jaan ho meri 😘",
    "Tum toh meri duniya ho 🌍",
    "Tum toh meri khushi ho 😁",
    "Oye shona, kahan gayab ho? 🥺",
    "Tum toh pyaar ke layak ho ❤️",
    "Tum toh meri dua ho 🤲",
    "Oye heroine, kya haal hai? 😍",
    "Aaj toh tumne aag laga di 🔥",
    "Tum toh dil ki raani ho 👑",
    "Tumhari baatein dil ko chhoo jati hain",
    "Oye cute, suno na 🥰",
    "Tum toh meri raat ka chand ho 🌙",
    "Tum toh dil ki dhadkan ho 💓",
    "Tum toh meri subah ho ☀️",
    "Oye jaanu, miss you 🥺",
    "Tum toh dil ke kareeb ho",
    "Zakhmi Sayar ka bot tumhe yaad kar raha tha 🥰",
    "Zakhmi ki shayari sunoge? Dil khush ho jayega 📝",
    "Zakhmi Sayar ki mehfil me swagat hai 🌟",
    "Zakhmi ka naam sunte hi dil garden ho jata hai ❤️",
    "Zakhmi Sayar ke liye ek like banta hai 👍",
    "Dil toota hai Zakhmi ka, tum mat todna 💔",
    "Tum Zakhmi ke dost ho isliye mere bhi dost ho 🤗",
    "Zakhmi Sayar ka dil bahut bada hai 💖",
    "Zakhmi Sayar ki taraf se salaam 🙏",
    "Zakhmi ka bot best hai 😎",
    "Zakhmi Sayar ki jaan ho tum 😘",
    "Zakhmi ki shayari, tumhari hansi 😂",
    "Tum Zakhmi ke bina adhoore ho 😜",
    "Zakhmi Sayar ka fan hu mai bhi 😍",
    "Zakhmi Sayar ki duniya me swagat hai 🌍",
    "Tum toh Zakhmi se bhi zyada cute ho 🙈",
    "Zakhmi Sayar - Shayari ka Badshah 📝",
    "Zakhmi ka status dekha kya? 🔥",
    "Zakhmi Sayar ko follow karo, maza ayega 😎"
  ];

  if (body.includes("owner") || body.includes("malik") || body.includes("zakhmi")) {
    return api.sendMessage("👑 OWNER: ZAKHMI SAYAR 🎸\n💖 FB: https://www.facebook.com/profile.php?id=61595007082014\n📝 Shayari ka Badshah", threadID, messageID);
  }

  const emojiReplies = {
    "😀": "khushi ke maare daant dikha raha hai 😀",
    "😃": "itna khush kyu hai 😃",
    "😄": "maza aa gaya kya 😄",
    "😁": "brush karke aaya hai kya 😁",
    "😆": "has has ke pagal ho gaya 😆",
    "😅": "paseena kyu aa raha hai 😅",
    "🤣": "pet phat jayega has has ke 🤣",
    "😂": "itna haso mat pyaar ho jayega 😂",
    "🙂": "halki si muskan 🙂",
    "🙃": "ulti khopdi 🙃",
    "😉": "aankh maar raha hai 😉",
    "😊": "sharmili muskan 😊",
    "😇": "itna shareef kab se 😇",
    "🥰": "pyaar baras raha hai 🥰",
    "😍": "IS NAZAR SE ZAKHMI KO DEKHO 😍",
    "🤩": "aankhon me sitare 🤩",
    "😘": "kissi de raha hai 😘 brush kiya?",
    "😗": "hawa me kissi 😗",
    "☺️": "sharma gaya ☺️",
    "😚": "kissi wala 😚",
    "😙": "kissi band karo 😙",
    "🥲": "hasi me rona 🥲",
    "🥹": "aansoo wala pyaar 🥹",
    "😋": "bhookh lagi hai kya 😋",
    "😛": "jeebh kyu dikha raha hai 😛",
    "😝": "naughty 😝",
    "😜": "zabaan mat nikal 😜",
    "🤪": "pagal ho gaya kya 🤪",
    "🤤": "muh se paani tapak raha hai 🤤",
    "😒": "samne dekh na 😒",
    "😏": "attitude dikha raha hai 😏",
    "🙄": "Zakhmi Boss busy hai 🙄",
    "😑": "boring lag raha hai kya 😑",
    "😶": "muh me dahi jama hai kya 😶",
    "😣": "pareshan kyu hai 😣",
    "😥": "udaas kyu hai 😥",
    "😮": "muh me makkhi ghus jayegi 😮",
    "😯": "hairan kyu hai 😯",
    "😪": "neend aa rahi hai kya 😪",
    "😫": "thak gaya kya 😫",
    "🥱": "neend aa rahi hai to so ja 🥱",
    "😴": "so ja raat ho gayi 😴",
    "😌": "sukoon mil gaya 😌",
    "😛": "jeebh mat nikal 😛",
    "🤗": "hug chahiye kya 🤗",
    "🤭": "muh band karke haso 🤭",
    "🫢": "sharma gaya 🫢",
    "🫣": "chup chup ke dekh raha hai 🫣",
    "🤫": "chup kisi ko mat batana 🤫",
    "🫡": "salam sahab 🫡",
    "🤥": "jhooth bol raha hai 🤥",
    "😶‍🌫️": "dhue me kho gaya 😶‍🌫️",
    "😬": "daant kyu dikha raha hai 😬",
    "😮‍💨": "lambi saans 😮‍💨",
    "😷": "mask laga le 😷",
    "🤒": "bukhar hai kya 🤒",
    "🤕": "chot lagi hai kya 🤕",
    "🤢": "ulti aa rahi hai kya 🤢",
    "🤮": "ulti kar di 🤮",
    "🤧": "naak saaf kar 🤧",
    "🥵": "garmi lag rahi hai 🥵",
    "🥶": "thand lag rahi hai 🥶",
    "🥴": "nashe me hai kya 🥴",
    "😵": "chakkar aa gaye 😵",
    "😵‍💫": "chakkar hi chakkar 😵‍💫",
    "🤯": "dimag fat gaya 🤯",
    "🤠": "cowboy ban gaya 🤠",
    "🥳": "party ho rahi hai 🥳",
    "🥸": "jasoos ban gaya 🥸",
    "😎": "chashma hata aankhein dikha 😎",
    "🤓": "padhaku 🤓",
    "🧐": "jasoos 🧐",
    "😕": "confuse hai kya 😕",
    "🫤": "mooh teda 🫤",
    "😟": "pareshan 😟",
    "🙁": "udaas 🙁",
    "☹️": "dukhi ☹️",
    "😲": "shock laga 😲",
    "😳": "sharma gaya 😳",
    "🥺": "masoom mat ban 🥺",
    "😢": "ro mat yaar mai hu na 😢",
    "😭": "rona band kar drama queen 😭",
    "😤": "gussa kyu kar raha hai 😤",
    "😠": "gussa thook de 😠",
    "😡": "chappal khaayega 😡",
    "🤬": "gali mat de Zakhmi ko bata dungi 🤬",
    "😱": "bhoot dekh liya kya 😱",
    "😨": "dar gaya kya 😨",
    "😰": "paseena aa gaya 😰",
    "❤️": "MEKO KALA DIL CHAHIYE ❤️",
    "🧡": "narangi dil 🧡",
    "💛": "peela dil 💛",
    "💚": "Ankho me pyaar 💚",
    "💙": "neela dil 💙",
    "💜": "jamuni dil 💜",
    "🖤": "kala dil wala sach wala pyaar 🖤",
    "🤍": "safed dil 🤍",
    "🤎": "chocolate dil 🤎",
    "💔": "dil toot gaya to fevicol se jod do 💔",
    "💕": "pyaar wala dil 💕",
    "💞": "do dil mil rahe hain 💞",
    "💓": "dhadak raha hai dil 💓",
    "💖": "chamakta dil 💖",
    "💝": "gift wala dil 💝",
    "💘": "teer wala dil 💘",
    "👍": "tusi awesome ho g 👍",
    "👎": "dislike kyu kiya 👎",
    "👌": "wah kya baat hai 👌",
    "✌️": "victory ✌️",
    "🤞": "cross finger 🤞",
    "🤟": "rockstar 🤟",
    "🤘": "rock on 🤘",
    "🤙": "call me 🤙",
    "👈": "kidhar ishara 👈",
    "👉": "udhar kya hai 👉",
    "👆": "upar kya hai 👆",
    "👇": "neeche kya hai 👇",
    "✋": "ruko zara ✋",
    "👋": "bye bye 👋",
    "👏": "taali bajao 👏",
    "🙌": "khushi mana raha hai 🙌",
    "👐": "khula dil 👐",
    "🤲": "dua maang raha hai 🤲",
    "🙏": "ja maaf kiya 🙏",
    "💪": "takath dikha raha hai 💪",
    "👀": "kya dekh raha hai 👀",
    "🐒": "bandar jaisi shakal 🐒",
    "🦁": "sher 🦁",
    "🔥": "aag laga di 🔥",
    "💯": "100% sahi 💯",
    "✨": "chamak raha hai ✨",
    "🌟": "star hai tu 🌟",
    "🎉": "party time 🎉",
    "🎊": "jashn 🎊",
    "🎁": "gift de raha hai kya 🎁",
    "🌹": "phool de raha hai 🌹",
    "🥀": "murjhaya phool 🥀",
    "💐": "guldasta 💐",
    "🌸": "phool jaisa dil 🌸",
    "🍫": "chocolate khila de 🍫",
    "🍕": "pizza khila de 🍕",
    "☕": "chai pila de ☕",
    "🌙": "chand 🌙",
    "💀": "khatam tata bye bye 💀",
    "👻": "bhoot aa gaya 👻",
    "💩": "tatti jaisi shakal 💩😂",
    "🤡": "joker ban gaya 🤡",
    "👽": "alien aa gaya 👽"
  };

  // HAR EMOJI KA REPLY - LOOP SE
  for (let e in emojiReplies) {
    if (raw.includes(e)) {
      return api.sendMessage(emojiReplies[e], threadID, messageID);
    }
  }

  if (body.startsWith("bot")) {
    return api.sendMessage(tl[Math.floor(Math.random() * tl.length)], threadID, messageID);
  }
};

module.exports.run = function() {}
